export default {
  login: 'john-smilga',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/john-smilga',
  html_url: 'https://github.com/john-smilga',
  followers_url: 'https://api.github.com/users/john-smilga/followers',
  following_url:
    'https://api.github.com/users/john-smilga/following{/other_user}',
  gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  repos_url: 'https://api.github.com/users/john-smilga/repos',
  events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/john-smilga/received_events',
  type: 'User',
  site_admin: false,
  name: 'John Smilga',
  company: 'Coding Addict',
  blog: 'www.johnsmilga.com',
  location: 'Los Angeles',
  email: null,
  hireable: null,
  bio: 'Creator of Coding Addict',
  twitter_username: 'john_smilga',
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
};
// export default {
//   login: "ReniePH",
//   id: 10185116,
//   node_id: "MDQ6VXNlcjEwMTg1MTE2",
//   avatar_url: "https://avatars.githubusercontent.com/u/10185116?v=4",
//   gravatar_id: "",
//   url: "https://api.github.com/users/ReniePH",
//   html_url: "https://github.com/ReniePH",
//   followers_url: "https://api.github.com/users/ReniePH/followers",
//   following_url: "https://api.github.com/users/ReniePH/following{/other_user}",
//   gists_url: "https://api.github.com/users/ReniePH/gists{/gist_id}",
//   starred_url: "https://api.github.com/users/ReniePH/starred{/owner}{/repo}",
//   subscriptions_url: "https://api.github.com/users/ReniePH/subscriptions",
//   organizations_url: "https://api.github.com/users/ReniePH/orgs",
//   repos_url: "https://api.github.com/users/ReniePH/repos",
//   events_url: "https://api.github.com/users/ReniePH/events{/privacy}",
//   received_events_url: "https://api.github.com/users/ReniePH/received_events",
//   type: "User",
//   site_admin: false,
//   name: null,
//   company: null,
//   blog: "",
//   location: null,
//   email: null,
//   hireable: true,
//   bio: "I am self taught developer / freelance fullstack developer.",
//   twitter_username: null,
//   public_repos: 26,
//   public_gists: 0,
//   followers: 0,
//   following: 0,
//   created_at: "2014-12-14T13:44:29Z",
//   updated_at: "2021-05-08T17:55:05Z"
//   };